In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("diabetes.csv")

In [6]:
df.head(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1

In [7]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [8]:
x=df.iloc[:,:-1].values

In [9]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [10]:
y=df.iloc[:,-1]

In [11]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [14]:
x=scaler.fit_transform(x)

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [86]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout

In [31]:
model = Sequential()
model.add(Dense(32, activation="relu", input_dim=8))
model.add(Dense(1, activation="sigmoid"))

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [33]:
model.fit (X_train,Y_train,batch_size=32,epochs=10,validation_data=(X_test,Y_test))

Epoch 1/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - accuracy: 0.4935 - loss: 0.7190 - val_accuracy: 0.6061 - val_loss: 0.6802
Epoch 2/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6182 - loss: 0.6683 - val_accuracy: 0.6580 - val_loss: 0.6378
Epoch 3/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6574 - loss: 0.6316 - val_accuracy: 0.6970 - val_loss: 0.6031
Epoch 4/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7002 - loss: 0.6011 - val_accuracy: 0.7316 - val_loss: 0.5755
Epoch 5/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.5771 - val_accuracy: 0.7532 - val_loss: 0.5544
Epoch 6/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7374 - loss: 0.5578 - val_accuracy: 0.7619 - val_loss: 0.5365
Epoch 7/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7430 - loss: 0.5423 - val_accuracy: 0.7662 - val_loss: 0.5206
Epoch 8/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7374 - loss: 0.5292 - val_accuracy: 0.7749 - val_loss: 0.5077
Epoch 9/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7393 - loss: 0.5187 - val_accuracy: 0.7879 - val_loss: 0.4977
Epoch 10/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7467 - loss: 0.5095 - val_accuracy: 0.7879 - val_loss: 0.4882

#1.How to select the optimizer
#2.How to decidei on hidden layers number
#3.how to decide the node numbers

#4. All in all in one model

In [40]:
!pip install -q keras-tuner

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 5.0 MB/s eta 0:00:00

In [41]:
import keras_tuner as kt

In [42]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32,
                  activation="relu",
                  input_dim=8
  ))

  model.add(Dense(1, activation="sigmoid"
  ))

  model.compile(optimizer=hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop', 'adadelta']),
                loss="binary_crossentropy", metrics=["accuracy"])

  return model

In [43]:
tuner = kt.RandomSearch(build_model, objective="val_accuracy", max_trials=5)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [45]:
tuner.search(X_train, Y_train, epochs=5, validation_data=(X_test, Y_test))

Trial 4 Complete [00h 00m 04s]
val_accuracy: 0.7532467246055603

Best val_accuracy So Far: 0.7532467246055603
Total elapsed time: 00h 00m 56s

In [46]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [49]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [50]:
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]
model = tuner.hypermodel.build(best_hps)

In [51]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [54]:
model.fit(X_train, Y_train, batch_size=32, epochs=100, initial_epoch=6)

Epoch 7/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - accuracy: 0.6182 - loss: 0.6886
Epoch 8/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6592 - loss: 0.6369
Epoch 9/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6760 - loss: 0.6025
Epoch 10/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6983 - loss: 0.5749
Epoch 11/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7039 - loss: 0.5528
Epoch 12/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7169 - loss: 0.5353
Epoch 13/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7225 - loss: 0.5209
Epoch 14/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7318 - loss: 0.5097
Epoch 15/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7412 - loss: 0.5004
Epoch 16/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7467 - loss: 0.4930
Epoch 17/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7505 - loss: 0.4867
Epoch 18/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7467 - loss: 0.4815
Epoch 19/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7635 - loss: 0.4780
Epoch 20/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7561 - loss: 0.4746
Epoch 21/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7598 - loss: 0.4717
Epoch 22/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7654 - loss: 0.4695
Epoch 23/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7654 - loss: 0.4675
Epoch 24/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7672 - loss: 0.4655
Epoch 25/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7654 - loss: 0.4644
Epoch 26/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7672 - loss: 0.4630
Epoch 27/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7691 - loss: 0.4618
Epoch 28/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7728 - loss: 0.4611
Epoch 29/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7765 - loss: 0.4600
Epoch 30/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7728 - loss: 0.4593
Epoch 31/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7765 - loss: 0.4586
Epoch 32/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7728 - loss: 0.4576
Epoch 33/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7747 - loss: 0.4568
Epoch 34/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7765 - loss: 0.4563
Epoch 35/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7765 - loss: 0.4555
Epoch 36/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7821 - loss: 0.4548
Epoch 37/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7784 - loss: 0.4544
Epoch 38/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7765 - loss: 0.4534
Epoch 39/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7765 - loss: 0.4532
Epoch 40/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7858 - loss: 0.4524
Epoch 41/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7784 - loss: 0.4517
Epoch 42/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7803 - loss: 0.4512
Epoch 43/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7784 - loss: 0.4508
Epoch 44/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7765 - loss: 0.4504
Epoch 45/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7784 - loss: 0.4496
Epoch 46/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7747 - loss: 0.4492
Epoch 47/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7747 - loss: 0.4490
Epoch 48/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7784 - loss: 0.4485
Epoch 49/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7765 - loss: 0.4480
Epoch 50/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7765 - loss: 0.4476
Epoch 51/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7784 - loss: 0.4471
Epoch 52/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7803 - loss: 0.4466
Epoch 53/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7784 - loss: 0.4462
Epoch 54/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7803 - loss: 0.4461
Epoch 55/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7821 - loss: 0.4457
Epoch 56/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7821 - loss: 0.4449
Epoch 57/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7784 - loss: 0.4447
Epoch 58/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7821 - loss: 0.4444
Epoch 59/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7821 - loss: 0.4439
Epoch 60/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7821 - loss: 0.4434
Epoch 61/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7821 - loss: 0.4431
Epoch 62/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7803 - loss: 0.4431
Epoch 63/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7858 - loss: 0.4428
Epoch 64/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7877 - loss: 0.4419
Epoch 65/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7840 - loss: 0.4415
Epoch 66/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7877 - loss: 0.4409
Epoch 67/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7858 - loss: 0.4410
Epoch 68/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7877 - loss: 0.4409
Epoch 69/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7877 - loss: 0.4402
Epoch 70/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7877 - loss: 0.4397
Epoch 71/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7952 - loss: 0.4389
Epoch 72/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7933 - loss: 0.4392
Epoch 73/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7952 - loss: 0.4384
Epoch 74/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7914 - loss: 0.4380
Epoch 75/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7970 - loss: 0.4379
Epoch 76/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7914 - loss: 0.4376
Epoch 77/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7933 - loss: 0.4371
Epoch 78/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7952 - loss: 0.4366
Epoch 79/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7970 - loss: 0.4365
Epoch 80/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7970 - loss: 0.4362
Epoch 81/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7914 - loss: 0.4357
Epoch 82/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7970 - loss: 0.4355
Epoch 83/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7952 - loss: 0.4349
Epoch 84/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7933 - loss: 0.4352
Epoch 85/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7970 - loss: 0.4346
Epoch 86/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7952 - loss: 0.4344
Epoch 87/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7952 - loss: 0.4339
Epoch 88/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7970 - loss: 0.4340
Epoch 89/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7933 - loss: 0.4335
Epoch 90/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7952 - loss: 0.4325
Epoch 91/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7933 - loss: 0.4330
Epoch 92/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7989 - loss: 0.4323
Epoch 93/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7970 - loss: 0.4323
Epoch 94/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7952 - loss: 0.4318
Epoch 95/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7970 - loss: 0.4318
Epoch 96/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7989 - loss: 0.4310
Epoch 97/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7989 - loss: 0.4309
Epoch 98/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8007 - loss: 0.4306
Epoch 99/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8007 - loss: 0.4305
Epoch 100/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8045 - loss: 0.4304

In [63]:
def build_model(hp):
  model = Sequential()

  # hp.Int needs a name (for tracking), then min_value, max_value, step
  # this tells the tuner to try unit counts from 8 to 128, in steps of 8
  # (i.e. 8, 16, 24, 32, ..., 128) and search for the best one
  units = hp.Int('units', min_value=8, max_value=128, step=8)

  model.add(Dense(units=units, activation="relu", input_dim=8))
  model.add(Dense(1, activation="sigmoid"))

  model.compile(optimizer="rmsprop", loss="binary_crossentropy", metrics=["accuracy"])

  return model

In [64]:
tuner = kt.RandomSearch(build_model, objective="val_accuracy", max_trials=5,directory="mydir",project_name="hamza")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [65]:
tuner.search(X_train, Y_train, epochs=5, validation_data=(X_test, Y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.6796537041664124

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 18s

In [66]:
tuner.get_best_hyperparameters()[0].values

{'units': 80}

In [67]:
def build_model(hp):
  model = Sequential()

  # first (input) layer — fixed size, always present
  model.add(Dense(80, activation="relu", input_dim=8))

  # hp.Int lets the tuner search how many hidden layers to add,
  # trying anywhere from 1 to 10 layers
  for i in range(hp.Int("num_layers", min_value=1, max_value=10)):
    # add one hidden layer per loop iteration
    model.add(Dense(80, activation="relu"))

  # output layer — single neuron for binary classification
  model.add(Dense(1, activation="sigmoid"))

  model.compile(optimizer="rmsprop", loss="binary_crossentropy", metrics=["accuracy"])

  return model

In [68]:
tuner = kt.RandomSearch(
    build_model,                  # the model-building function to search over
    objective="val_accuracy",     # metric the tuner tries to optimize
    max_trials=4,                 # number of different hyperparameter combos to try
    directory="mydir",            # folder to store search results/logs
    project_name="num_layers"     # subfolder name for this specific search
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [69]:
tuner.search(
    X_train, Y_train,             # training data and labels
    epochs=5,                     # number of epochs to train each trial for
    validation_data=(X_test, Y_test)  # data used to evaluate each trial's performance
)

Trial 4 Complete [00h 00m 06s]
val_accuracy: 0.8095238208770752

Best val_accuracy So Far: 0.8181818127632141
Total elapsed time: 00h 00m 21s

In [70]:
tuner.get_best_hyperparameters()[0].values
# this is for the recent task ( number of layers)

{'num_layers': 6}

In [71]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 18 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [73]:
model.fit(X_train, Y_train, epochs=100, initial_epoch=6, validation_data=(X_test, Y_test))

Epoch 7/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 5s 89ms/step - accuracy: 0.7747 - loss: 0.4577 - val_accuracy: 0.7792 - val_loss: 0.4736
Epoch 8/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8026 - loss: 0.4376 - val_accuracy: 0.7965 - val_loss: 0.4371
Epoch 9/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8063 - loss: 0.4252 - val_accuracy: 0.8009 - val_loss: 0.4373
Epoch 10/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8175 - loss: 0.4067 - val_accuracy: 0.8052 - val_loss: 0.4501
Epoch 11/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8324 - loss: 0.3896 - val_accuracy: 0.7749 - val_loss: 0.4721
Epoch 12/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8361 - loss: 0.3821 - val_accuracy: 0.7879 - val_loss: 0.4576
Epoch 13/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8436 - loss: 0.3793 - val_accuracy: 0.7619 - val_loss: 0.4927
Epoch 14/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8417 - loss: 0.3616 - val_accuracy: 0.7403 - val_loss: 0.5069
Epoch 15/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8510 - loss: 0.3550 - val_accuracy: 0.7662 - val_loss: 0.4967
Epoch 16/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8510 - loss: 0.3396 - val_accuracy: 0.7922 - val_loss: 0.4622
Epoch 17/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8827 - loss: 0.2986 - val_accuracy: 0.7749 - val_loss: 0.4891
Epoch 18/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8547 - loss: 0.3209 - val_accuracy: 0.7749 - val_loss: 0.5022
Epoch 19/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8790 - loss: 0.2874 - val_accuracy: 0.7749 - val_loss: 0.5671
Epoch 20/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8845 - loss: 0.2658 - val_accuracy: 0.7662 - val_loss: 0.5182
Epoch 21/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9013 - loss: 0.2479 - val_accuracy: 0.6926 - val_loss: 0.7298
Epoch 22/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8957 - loss: 0.2679 - val_accuracy: 0.7749 - val_loss: 0.5902
Epoch 23/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9162 - loss: 0.2292 - val_accuracy: 0.7749 - val_loss: 0.5648
Epoch 24/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9143 - loss: 0.2323 - val_accuracy: 0.7532 - val_loss: 0.5323
Epoch 25/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9032 - loss: 0.2563 - val_accuracy: 0.7835 - val_loss: 0.5543
Epoch 26/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9274 - loss: 0.2227 - val_accuracy: 0.7403 - val_loss: 0.7244
Epoch 27/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9311 - loss: 0.1938 - val_accuracy: 0.7619 - val_loss: 0.6349
Epoch 28/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8976 - loss: 0.2619 - val_accuracy: 0.7532 - val_loss: 0.6037
Epoch 29/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9404 - loss: 0.1696 - val_accuracy: 0.7922 - val_loss: 0.6388
Epoch 30/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9404 - loss: 0.1619 - val_accuracy: 0.7186 - val_loss: 0.9507
Epoch 31/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9274 - loss: 0.2306 - val_accuracy: 0.7143 - val_loss: 0.8527
Epoch 32/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1485 - val_accuracy: 0.7619 - val_loss: 0.7470
Epoch 33/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9367 - loss: 0.1736 - val_accuracy: 0.7662 - val_loss: 0.7126
Epoch 34/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9385 - loss: 0.1782 - val_accuracy: 0.7835 - val_loss: 0.7218
Epoch 35/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9479 - loss: 0.1530 - val_accuracy: 0.7749 - val_loss: 0.7665
Epoch 36/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9553 - loss: 0.1243 - val_accuracy: 0.7532 - val_loss: 0.8342
Epoch 37/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9497 - loss: 0.1545 - val_accuracy: 0.7706 - val_loss: 0.7236
Epoch 38/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9665 - loss: 0.1081 - val_accuracy: 0.7749 - val_loss: 0.8729
Epoch 39/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9441 - loss: 0.1295 - val_accuracy: 0.7792 - val_loss: 0.8645
Epoch 40/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9590 - loss: 0.1000 - val_accuracy: 0.7316 - val_loss: 1.0814
Epoch 41/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9683 - loss: 0.1112 - val_accuracy: 0.7792 - val_loss: 0.8905
Epoch 42/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9646 - loss: 0.0934 - val_accuracy: 0.7273 - val_loss: 1.4996
Epoch 43/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9683 - loss: 0.0929 - val_accuracy: 0.6970 - val_loss: 1.5710
Epoch 44/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9441 - loss: 0.1689 - val_accuracy: 0.7662 - val_loss: 1.0132
Epoch 45/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9739 - loss: 0.0714 - val_accuracy: 0.7359 - val_loss: 1.3963
Epoch 46/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9590 - loss: 0.1086 - val_accuracy: 0.7489 - val_loss: 1.2583
Epoch 47/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9795 - loss: 0.0577 - val_accuracy: 0.7835 - val_loss: 1.1519
Epoch 48/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9814 - loss: 0.0618 - val_accuracy: 0.7619 - val_loss: 1.2693
Epoch 49/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9497 - loss: 0.1584 - val_accuracy: 0.7619 - val_loss: 1.1926
Epoch 50/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9777 - loss: 0.0516 - val_accuracy: 0.7792 - val_loss: 1.1452
Epoch 51/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9944 - loss: 0.0249 - val_accuracy: 0.7576 - val_loss: 1.9528
Epoch 52/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9553 - loss: 0.1152 - val_accuracy: 0.7662 - val_loss: 1.2151
Epoch 53/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9814 - loss: 0.0379 - val_accuracy: 0.7576 - val_loss: 1.2807
Epoch 54/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9832 - loss: 0.0603 - val_accuracy: 0.7229 - val_loss: 1.7215
Epoch 55/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9739 - loss: 0.0649 - val_accuracy: 0.7403 - val_loss: 1.6933
Epoch 56/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9739 - loss: 0.0683 - val_accuracy: 0.7749 - val_loss: 1.3966
Epoch 57/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9851 - loss: 0.0445 - val_accuracy: 0.7359 - val_loss: 1.7315
Epoch 58/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9888 - loss: 0.0375 - val_accuracy: 0.7316 - val_loss: 1.7066
Epoch 59/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9907 - loss: 0.0514 - val_accuracy: 0.7403 - val_loss: 1.4988
Epoch 60/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9795 - loss: 0.0638 - val_accuracy: 0.7403 - val_loss: 1.6458
Epoch 61/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9888 - loss: 0.0380 - val_accuracy: 0.7576 - val_loss: 1.4077
Epoch 62/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9795 - loss: 0.0641 - val_accuracy: 0.7316 - val_loss: 1.3530
Epoch 63/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9609 - loss: 0.0913 - val_accuracy: 0.7835 - val_loss: 1.2761
Epoch 64/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9870 - loss: 0.0310 - val_accuracy: 0.7619 - val_loss: 1.3322
Epoch 65/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9963 - loss: 0.0147 - val_accuracy: 0.7576 - val_loss: 1.6260
Epoch 66/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9721 - loss: 0.0730 - val_accuracy: 0.7576 - val_loss: 1.4907
Epoch 67/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9907 - loss: 0.0182 - val_accuracy: 0.7619 - val_loss: 1.6027
Epoch 68/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0620 - val_accuracy: 0.7446 - val_loss: 1.8502
Epoch 69/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9907 - loss: 0.0518 - val_accuracy: 0.7446 - val_loss: 1.5880
Epoch 70/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9888 - loss: 0.0344 - val_accuracy: 0.7446 - val_loss: 2.4985
Epoch 71/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9814 - loss: 0.0578 - val_accuracy: 0.7489 - val_loss: 1.7955
Epoch 72/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0099 - val_accuracy: 0.7662 - val_loss: 1.6519
Epoch 73/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9944 - loss: 0.0221 - val_accuracy: 0.7446 - val_loss: 2.0960
Epoch 74/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9758 - loss: 0.0950 - val_accuracy: 0.7576 - val_loss: 1.7334
Epoch 75/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9981 - loss: 0.0072 - val_accuracy: 0.7576 - val_loss: 1.7699
Epoch 76/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9888 - loss: 0.0555 - val_accuracy: 0.7229 - val_loss: 1.7172
Epoch 77/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9814 - loss: 0.0466 - val_accuracy: 0.7446 - val_loss: 1.5867
Epoch 78/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9926 - loss: 0.0148 - val_accuracy: 0.7359 - val_loss: 1.8183
Epoch 79/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9944 - loss: 0.0202 - val_accuracy: 0.7489 - val_loss: 1.8177
Epoch 80/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9888 - loss: 0.0572 - val_accuracy: 0.7403 - val_loss: 2.0024
Epoch 81/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9963 - loss: 0.0111 - val_accuracy: 0.7532 - val_loss: 1.6747
Epoch 82/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9777 - loss: 0.0767 - val_accuracy: 0.7576 - val_loss: 1.6372
Epoch 83/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9888 - loss: 0.0213 - val_accuracy: 0.7532 - val_loss: 1.6633
Epoch 84/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9795 - loss: 0.0663 - val_accuracy: 0.7706 - val_loss: 1.4975
Epoch 85/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9814 - loss: 0.0559 - val_accuracy: 0.7489 - val_loss: 1.9282
Epoch 86/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9944 - loss: 0.0154 - val_accuracy: 0.7489 - val_loss: 1.7770
Epoch 87/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0028 - val_accuracy: 0.7619 - val_loss: 1.8614
Epoch 88/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9926 - loss: 0.0311 - val_accuracy: 0.7229 - val_loss: 1.8770
Epoch 89/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9907 - loss: 0.0354 - val_accuracy: 0.7143 - val_loss: 2.0016
Epoch 90/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9888 - loss: 0.0348 - val_accuracy: 0.7316 - val_loss: 2.1172
Epoch 91/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9944 - loss: 0.0111 - val_accuracy: 0.7706 - val_loss: 1.7203
Epoch 92/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0262 - val_accuracy: 0.7662 - val_loss: 1.9470
Epoch 93/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9944 - loss: 0.0185 - val_accuracy: 0.7446 - val_loss: 1.9564
Epoch 94/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9963 - loss: 0.0124 - val_accuracy: 0.7576 - val_loss: 2.1042
Epoch 95/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9926 - loss: 0.0141 - val_accuracy: 0.7706 - val_loss: 2.2636
Epoch 96/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9981 - loss: 0.0055 - val_accuracy: 0.7446 - val_loss: 1.9419
Epoch 97/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9926 - loss: 0.0458 - val_accuracy: 0.7749 - val_loss: 1.8653
Epoch 98/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9907 - loss: 0.0226 - val_accuracy: 0.7403 - val_loss: 2.3756
Epoch 99/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9702 - loss: 0.1045 - val_accuracy: 0.7446 - val_loss: 1.9389
Epoch 100/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9963 - loss: 0.0095 - val_accuracy: 0.7532 - val_loss: 2.0838

In [89]:
def build_model(hp):
  model = Sequential()

  counter = 0

  # hp.Int('num_layers', min_value=1, max_value=10) searches how many
  # hidden layers to add (must be INSIDE hp.Int, not passed to range())
  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):

    if counter == 0:
      # first hidden layer — needs input_dim since it's right after the input
      model.add(
          Dense(
              hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
              activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid']),
              input_dim=8
          )
      )

      model.add(Dropout(hp.Choice('dropout' + str(i), values=[.1, .2, .3, .4, .5, .6, .7])))
    else:
      # subsequent hidden layers — no input_dim needed, Keras infers shape
      model.add(
          Dense(
              hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
              activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid'])
          )
      )
      model.add(Dropout(hp.Choice('dropout' + str(i), values=[.1, .2, .3, .4, .5, .6, .7])))
    counter += 1

  # output layer — single neuron for binary classification
  model.add(Dense(1, activation='sigmoid'))

  model.compile(
      optimizer=hp.Choice('optimizer', values=['rmsprop', 'adam', 'sgd', 'nadam', 'adadelta']),
      loss='binary_crossentropy',
      metrics=['accuracy']
  )

  return model

In [90]:
tuner = kt.RandomSearch(
    build_model,                  # function that builds and compiles the model
    objective="val_accuracy",     # metric the tuner tries to optimize
    max_trials=3,                 # number of different hyperparameter combos to try
    directory="mydir",            # folder to store search results/logs
    project_name="final1"          # subfolder name for this specific search
)

In [91]:
tuner.search(X_train,Y_train,epochs=5,validation_data=(X_test,Y_test))

Trial 3 Complete [00h 00m 05s]
val_accuracy: 0.7272727489471436

Best val_accuracy So Far: 0.7272727489471436
Total elapsed time: 00h 00m 30s

In [92]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 1,
 'units0': 32,
 'activation0': 'relu',
 'dropout0': 0.6,
 'optimizer': 'adam',
 'units1': 80,
 'activation1': 'tanh',
 'dropout1': 0.2,
 'units2': 24,
 'activation2': 'tanh',
 'dropout2': 0.2,
 'units3': 80,
 'activation3': 'relu',
 'dropout3': 0.2,
 'units4': 24,
 'activation4': 'relu',
 'dropout4': 0.5,
 'units5': 80,
 'activation5': 'relu',
 'dropout5': 0.1,
 'units6': 72,
 'activation6': 'tanh',
 'dropout6': 0.1}

In [93]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [94]:
model.fit(X_train, Y_train, epochs=200, initial_epoch=6, validation_data=(X_test, Y_test))

Epoch 7/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 3s 91ms/step - accuracy: 0.6704 - loss: 0.6062 - val_accuracy: 0.7316 - val_loss: 0.5449
Epoch 8/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6723 - loss: 0.6059 - val_accuracy: 0.7532 - val_loss: 0.5293
Epoch 9/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6778 - loss: 0.6036 - val_accuracy: 0.7706 - val_loss: 0.5187
Epoch 10/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7151 - loss: 0.5833 - val_accuracy: 0.7706 - val_loss: 0.5101
Epoch 11/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7207 - loss: 0.5586 - val_accuracy: 0.7749 - val_loss: 0.5039
Epoch 12/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7356 - loss: 0.5341 - val_accuracy: 0.7792 - val_loss: 0.4965
Epoch 13/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7188 - loss: 0.5602 - val_accuracy: 0.7835 - val_loss: 0.4907
Epoch 14/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7263 - loss: 0.5516 - val_accuracy: 0.7879 - val_loss: 0.4875
Epoch 15/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7225 - loss: 0.5308 - val_accuracy: 0.7835 - val_loss: 0.4829
Epoch 16/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7374 - loss: 0.5407 - val_accuracy: 0.7835 - val_loss: 0.4792
Epoch 17/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7207 - loss: 0.5296 - val_accuracy: 0.7792 - val_loss: 0.4770
Epoch 18/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7449 - loss: 0.5323 - val_accuracy: 0.7835 - val_loss: 0.4748
Epoch 19/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7430 - loss: 0.5298 - val_accuracy: 0.7835 - val_loss: 0.4728
Epoch 20/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7467 - loss: 0.5297 - val_accuracy: 0.7792 - val_loss: 0.4710
Epoch 21/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7523 - loss: 0.5034 - val_accuracy: 0.7792 - val_loss: 0.4692
Epoch 22/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7467 - loss: 0.5160 - val_accuracy: 0.7835 - val_loss: 0.4679
Epoch 23/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7374 - loss: 0.5255 - val_accuracy: 0.7922 - val_loss: 0.4663
Epoch 24/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7225 - loss: 0.5289 - val_accuracy: 0.7835 - val_loss: 0.4665
Epoch 25/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7430 - loss: 0.5236 - val_accuracy: 0.7835 - val_loss: 0.4657
Epoch 26/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7281 - loss: 0.5366 - val_accuracy: 0.7835 - val_loss: 0.4657
Epoch 27/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7598 - loss: 0.5205 - val_accuracy: 0.7835 - val_loss: 0.4653
Epoch 28/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7356 - loss: 0.5242 - val_accuracy: 0.7835 - val_loss: 0.4642
Epoch 29/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7635 - loss: 0.5063 - val_accuracy: 0.7922 - val_loss: 0.4633
Epoch 30/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7523 - loss: 0.5197 - val_accuracy: 0.7922 - val_loss: 0.4626
Epoch 31/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7449 - loss: 0.5211 - val_accuracy: 0.7922 - val_loss: 0.4622
Epoch 32/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7449 - loss: 0.5043 - val_accuracy: 0.7879 - val_loss: 0.4614
Epoch 33/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7654 - loss: 0.4961 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 34/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7654 - loss: 0.5041 - val_accuracy: 0.7922 - val_loss: 0.4608
Epoch 35/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7654 - loss: 0.5084 - val_accuracy: 0.7922 - val_loss: 0.4606
Epoch 36/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7598 - loss: 0.5039 - val_accuracy: 0.7965 - val_loss: 0.4605
Epoch 37/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7412 - loss: 0.4965 - val_accuracy: 0.7879 - val_loss: 0.4594
Epoch 38/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7616 - loss: 0.5011 - val_accuracy: 0.7835 - val_loss: 0.4589
Epoch 39/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7635 - loss: 0.5064 - val_accuracy: 0.7879 - val_loss: 0.4582
Epoch 40/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7672 - loss: 0.5079 - val_accuracy: 0.7879 - val_loss: 0.4577
Epoch 41/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7561 - loss: 0.5037 - val_accuracy: 0.7879 - val_loss: 0.4573
Epoch 42/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7542 - loss: 0.5109 - val_accuracy: 0.7879 - val_loss: 0.4570
Epoch 43/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7523 - loss: 0.4902 - val_accuracy: 0.7965 - val_loss: 0.4560
Epoch 44/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7579 - loss: 0.5012 - val_accuracy: 0.7965 - val_loss: 0.4554
Epoch 45/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7728 - loss: 0.4809 - val_accuracy: 0.7965 - val_loss: 0.4545
Epoch 46/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7579 - loss: 0.4915 - val_accuracy: 0.7965 - val_loss: 0.4542
Epoch 47/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7765 - loss: 0.5005 - val_accuracy: 0.7879 - val_loss: 0.4540
Epoch 48/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7635 - loss: 0.4824 - val_accuracy: 0.7835 - val_loss: 0.4542
Epoch 49/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7449 - loss: 0.4866 - val_accuracy: 0.7835 - val_loss: 0.4544
Epoch 50/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7709 - loss: 0.4910 - val_accuracy: 0.7835 - val_loss: 0.4539
Epoch 51/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7598 - loss: 0.4829 - val_accuracy: 0.7835 - val_loss: 0.4538
Epoch 52/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7709 - loss: 0.4971 - val_accuracy: 0.7835 - val_loss: 0.4543
Epoch 53/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7635 - loss: 0.4975 - val_accuracy: 0.7835 - val_loss: 0.4544
Epoch 54/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7486 - loss: 0.4979 - val_accuracy: 0.7835 - val_loss: 0.4545
Epoch 55/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7654 - loss: 0.4861 - val_accuracy: 0.7835 - val_loss: 0.4540
Epoch 56/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7523 - loss: 0.5095 - val_accuracy: 0.7835 - val_loss: 0.4533
Epoch 57/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7747 - loss: 0.4681 - val_accuracy: 0.7835 - val_loss: 0.4520
Epoch 58/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7803 - loss: 0.4718 - val_accuracy: 0.7879 - val_loss: 0.4517
Epoch 59/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7709 - loss: 0.5078 - val_accuracy: 0.7835 - val_loss: 0.4519
Epoch 60/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7635 - loss: 0.4790 - val_accuracy: 0.7792 - val_loss: 0.4528
Epoch 61/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7691 - loss: 0.4893 - val_accuracy: 0.7835 - val_loss: 0.4532
Epoch 62/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7635 - loss: 0.5007 - val_accuracy: 0.7835 - val_loss: 0.4532
Epoch 63/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7765 - loss: 0.4779 - val_accuracy: 0.7835 - val_loss: 0.4530
Epoch 64/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7505 - loss: 0.4961 - val_accuracy: 0.7749 - val_loss: 0.4527
Epoch 65/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7579 - loss: 0.4755 - val_accuracy: 0.7792 - val_loss: 0.4518
Epoch 66/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7654 - loss: 0.4959 - val_accuracy: 0.7835 - val_loss: 0.4508
Epoch 67/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7784 - loss: 0.4790 - val_accuracy: 0.7879 - val_loss: 0.4502
Epoch 68/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7598 - loss: 0.4878 - val_accuracy: 0.7879 - val_loss: 0.4499
Epoch 69/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7877 - loss: 0.4726 - val_accuracy: 0.7835 - val_loss: 0.4493
Epoch 70/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7598 - loss: 0.4785 - val_accuracy: 0.7835 - val_loss: 0.4490
Epoch 71/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7523 - loss: 0.5151 - val_accuracy: 0.7835 - val_loss: 0.4494
Epoch 72/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7561 - loss: 0.4930 - val_accuracy: 0.7835 - val_loss: 0.4504
Epoch 73/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7635 - loss: 0.4739 - val_accuracy: 0.7792 - val_loss: 0.4506
Epoch 74/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7747 - loss: 0.4722 - val_accuracy: 0.7792 - val_loss: 0.4506
Epoch 75/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7654 - loss: 0.4736 - val_accuracy: 0.7792 - val_loss: 0.4508
Epoch 76/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7598 - loss: 0.4681 - val_accuracy: 0.7792 - val_loss: 0.4511
Epoch 77/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7579 - loss: 0.4738 - val_accuracy: 0.7792 - val_loss: 0.4506
Epoch 78/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7616 - loss: 0.4819 - val_accuracy: 0.7792 - val_loss: 0.4511
Epoch 79/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7616 - loss: 0.4862 - val_accuracy: 0.7792 - val_loss: 0.4515
Epoch 80/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7561 - loss: 0.4924 - val_accuracy: 0.7792 - val_loss: 0.4511
Epoch 81/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7561 - loss: 0.4642 - val_accuracy: 0.7792 - val_loss: 0.4506
Epoch 82/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7616 - loss: 0.4832 - val_accuracy: 0.7792 - val_loss: 0.4514
Epoch 83/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7821 - loss: 0.4851 - val_accuracy: 0.7792 - val_loss: 0.4512
Epoch 84/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7747 - loss: 0.4823 - val_accuracy: 0.7792 - val_loss: 0.4512
Epoch 85/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7747 - loss: 0.4713 - val_accuracy: 0.7792 - val_loss: 0.4508
Epoch 86/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7691 - loss: 0.4804 - val_accuracy: 0.7792 - val_loss: 0.4503
Epoch 87/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7803 - loss: 0.4836 - val_accuracy: 0.7792 - val_loss: 0.4499
Epoch 88/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7598 - loss: 0.4895 - val_accuracy: 0.7792 - val_loss: 0.4497
Epoch 89/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7691 - loss: 0.4896 - val_accuracy: 0.7792 - val_loss: 0.4503
Epoch 90/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7579 - loss: 0.4901 - val_accuracy: 0.7835 - val_loss: 0.4513
Epoch 91/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7672 - loss: 0.4764 - val_accuracy: 0.7835 - val_loss: 0.4513
Epoch 92/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7598 - loss: 0.4691 - val_accuracy: 0.7879 - val_loss: 0.4510
Epoch 93/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7896 - loss: 0.4725 - val_accuracy: 0.7879 - val_loss: 0.4506
Epoch 94/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7709 - loss: 0.4901 - val_accuracy: 0.7835 - val_loss: 0.4505
Epoch 95/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7561 - loss: 0.4849 - val_accuracy: 0.7835 - val_loss: 0.4502
Epoch 96/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7654 - loss: 0.4819 - val_accuracy: 0.7835 - val_loss: 0.4503
Epoch 97/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7989 - loss: 0.4536 - val_accuracy: 0.7835 - val_loss: 0.4498
Epoch 98/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7765 - loss: 0.4725 - val_accuracy: 0.7835 - val_loss: 0.4494
Epoch 99/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7784 - loss: 0.4597 - val_accuracy: 0.7835 - val_loss: 0.4487
Epoch 100/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7784 - loss: 0.4779 - val_accuracy: 0.7835 - val_loss: 0.4479
Epoch 101/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7672 - loss: 0.4853 - val_accuracy: 0.7879 - val_loss: 0.4484
Epoch 102/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7765 - loss: 0.4928 - val_accuracy: 0.7835 - val_loss: 0.4486
Epoch 103/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7598 - loss: 0.4687 - val_accuracy: 0.7835 - val_loss: 0.4489
Epoch 104/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7784 - loss: 0.4649 - val_accuracy: 0.7835 - val_loss: 0.4490
Epoch 105/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7877 - loss: 0.4760 - val_accuracy: 0.7835 - val_loss: 0.4488
Epoch 106/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7728 - loss: 0.4814 - val_accuracy: 0.7835 - val_loss: 0.4483
Epoch 107/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7840 - loss: 0.4771 - val_accuracy: 0.7835 - val_loss: 0.4480
Epoch 108/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7635 - loss: 0.4729 - val_accuracy: 0.7835 - val_loss: 0.4478
Epoch 109/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7672 - loss: 0.4925 - val_accuracy: 0.7835 - val_loss: 0.4481
Epoch 110/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7709 - loss: 0.4646 - val_accuracy: 0.7835 - val_loss: 0.4482
Epoch 111/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7561 - loss: 0.4909 - val_accuracy: 0.7835 - val_loss: 0.4485
Epoch 112/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7709 - loss: 0.4687 - val_accuracy: 0.7835 - val_loss: 0.4481
Epoch 113/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7654 - loss: 0.4801 - val_accuracy: 0.7835 - val_loss: 0.4479
Epoch 114/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7709 - loss: 0.4668 - val_accuracy: 0.7879 - val_loss: 0.4474
Epoch 115/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7709 - loss: 0.4724 - val_accuracy: 0.7879 - val_loss: 0.4473
Epoch 116/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7691 - loss: 0.4731 - val_accuracy: 0.7835 - val_loss: 0.4469
Epoch 117/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7858 - loss: 0.4665 - val_accuracy: 0.7879 - val_loss: 0.4464
Epoch 118/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7896 - loss: 0.4669 - val_accuracy: 0.7879 - val_loss: 0.4456
Epoch 119/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7654 - loss: 0.4770 - val_accuracy: 0.7879 - val_loss: 0.4453
Epoch 120/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7672 - loss: 0.4749 - val_accuracy: 0.7835 - val_loss: 0.4452
Epoch 121/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7598 - loss: 0.4823 - val_accuracy: 0.7835 - val_loss: 0.4463
Epoch 122/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7803 - loss: 0.4787 - val_accuracy: 0.7835 - val_loss: 0.4462
Epoch 123/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7728 - loss: 0.4660 - val_accuracy: 0.7835 - val_loss: 0.4452
Epoch 124/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7728 - loss: 0.4754 - val_accuracy: 0.7792 - val_loss: 0.4454
Epoch 125/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7635 - loss: 0.4800 - val_accuracy: 0.7792 - val_loss: 0.4450
Epoch 126/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7691 - loss: 0.4761 - val_accuracy: 0.7792 - val_loss: 0.4452
Epoch 127/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7691 - loss: 0.4739 - val_accuracy: 0.7792 - val_loss: 0.4456
Epoch 128/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7598 - loss: 0.4866 - val_accuracy: 0.7792 - val_loss: 0.4449
Epoch 129/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7709 - loss: 0.4771 - val_accuracy: 0.7792 - val_loss: 0.4446
Epoch 130/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7858 - loss: 0.4707 - val_accuracy: 0.7792 - val_loss: 0.4445
Epoch 131/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7691 - loss: 0.4808 - val_accuracy: 0.7792 - val_loss: 0.4446
Epoch 132/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7765 - loss: 0.4744 - val_accuracy: 0.7792 - val_loss: 0.4440
Epoch 133/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7654 - loss: 0.4596 - val_accuracy: 0.7792 - val_loss: 0.4438
Epoch 134/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7728 - loss: 0.4789 - val_accuracy: 0.7792 - val_loss: 0.4447
Epoch 135/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7803 - loss: 0.4854 - val_accuracy: 0.7792 - val_loss: 0.4443
Epoch 136/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7598 - loss: 0.4662 - val_accuracy: 0.7835 - val_loss: 0.4445
Epoch 137/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7635 - loss: 0.4810 - val_accuracy: 0.7835 - val_loss: 0.4447
Epoch 138/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7840 - loss: 0.4550 - val_accuracy: 0.7835 - val_loss: 0.4451
Epoch 139/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7672 - loss: 0.4774 - val_accuracy: 0.7835 - val_loss: 0.4449
Epoch 140/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7858 - loss: 0.4542 - val_accuracy: 0.7835 - val_loss: 0.4451
Epoch 141/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7784 - loss: 0.4767 - val_accuracy: 0.7835 - val_loss: 0.4449
Epoch 142/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7821 - loss: 0.4729 - val_accuracy: 0.7792 - val_loss: 0.4441
Epoch 143/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7635 - loss: 0.4859 - val_accuracy: 0.7792 - val_loss: 0.4446
Epoch 144/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7765 - loss: 0.4785 - val_accuracy: 0.7835 - val_loss: 0.4449
Epoch 145/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7784 - loss: 0.4796 - val_accuracy: 0.7835 - val_loss: 0.4453
Epoch 146/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7654 - loss: 0.4717 - val_accuracy: 0.7792 - val_loss: 0.4457
Epoch 147/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7858 - loss: 0.4658 - val_accuracy: 0.7835 - val_loss: 0.4458
Epoch 148/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7747 - loss: 0.4559 - val_accuracy: 0.7835 - val_loss: 0.4457
Epoch 149/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7561 - loss: 0.4865 - val_accuracy: 0.7792 - val_loss: 0.4450
Epoch 150/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7765 - loss: 0.4757 - val_accuracy: 0.7835 - val_loss: 0.4457
Epoch 151/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7840 - loss: 0.4625 - val_accuracy: 0.7835 - val_loss: 0.4454
Epoch 152/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7728 - loss: 0.4636 - val_accuracy: 0.7835 - val_loss: 0.4450
Epoch 153/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7821 - loss: 0.4555 - val_accuracy: 0.7835 - val_loss: 0.4448
Epoch 154/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7747 - loss: 0.4628 - val_accuracy: 0.7792 - val_loss: 0.4454
Epoch 155/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7765 - loss: 0.4816 - val_accuracy: 0.7835 - val_loss: 0.4449
Epoch 156/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7803 - loss: 0.4682 - val_accuracy: 0.7835 - val_loss: 0.4450
Epoch 157/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7896 - loss: 0.4622 - val_accuracy: 0.7835 - val_loss: 0.4453
Epoch 158/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7672 - loss: 0.4601 - val_accuracy: 0.7835 - val_loss: 0.4456
Epoch 159/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7821 - loss: 0.4585 - val_accuracy: 0.7835 - val_loss: 0.4459
Epoch 160/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7784 - loss: 0.4524 - val_accuracy: 0.7835 - val_loss: 0.4457
Epoch 161/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7654 - loss: 0.4620 - val_accuracy: 0.7835 - val_loss: 0.4450
Epoch 162/200